package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AdminLedgers generated by hbm2java
 */
public class AdminLedgers implements java.io.Serializable {

	private Long ledgerId;
	private Integer custId;
	private String custName;
	private Integer resId;
	private String resName;
	private Integer assocId;
	private String assocName;
	private Integer orderNum;
	private Integer ledgerNum;
	private Date ledgerDate;
	private Float income;
	private String inMethod;
	private String inNote;
	private Float expense;
	private String exMethod;
	private String exNote;
	private String note;
	private Float balance;

	public AdminLedgers() {
	}

	public AdminLedgers(Integer custId, String custName, Integer resId, String resName, Integer assocId,
			String assocName, Integer orderNum, Integer ledgerNum, Date ledgerDate, Float income, String inMethod,
			String inNote, Float expense, String exMethod, String exNote, String note, Float balance) {
		this.custId = custId;
		this.custName = custName;
		this.resId = resId;
		this.resName = resName;
		this.assocId = assocId;
		this.assocName = assocName;
		this.orderNum = orderNum;
		this.ledgerNum = ledgerNum;
		this.ledgerDate = ledgerDate;
		this.income = income;
		this.inMethod = inMethod;
		this.inNote = inNote;
		this.expense = expense;
		this.exMethod = exMethod;
		this.exNote = exNote;
		this.note = note;
		this.balance = balance;
	}

	public Long getLedgerId() {
		return this.ledgerId;
	}

	public void setLedgerId(Long ledgerId) {
		this.ledgerId = ledgerId;
	}

	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public Integer getAssocId() {
		return this.assocId;
	}

	public void setAssocId(Integer assocId) {
		this.assocId = assocId;
	}

	public String getAssocName() {
		return this.assocName;
	}

	public void setAssocName(String assocName) {
		this.assocName = assocName;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getLedgerNum() {
		return this.ledgerNum;
	}

	public void setLedgerNum(Integer ledgerNum) {
		this.ledgerNum = ledgerNum;
	}

	public Date getLedgerDate() {
		return this.ledgerDate;
	}

	public void setLedgerDate(Date ledgerDate) {
		this.ledgerDate = ledgerDate;
	}

	public Float getIncome() {
		return this.income;
	}

	public void setIncome(Float income) {
		this.income = income;
	}

	public String getInMethod() {
		return this.inMethod;
	}

	public void setInMethod(String inMethod) {
		this.inMethod = inMethod;
	}

	public String getInNote() {
		return this.inNote;
	}

	public void setInNote(String inNote) {
		this.inNote = inNote;
	}

	public Float getExpense() {
		return this.expense;
	}

	public void setExpense(Float expense) {
		this.expense = expense;
	}

	public String getExMethod() {
		return this.exMethod;
	}

	public void setExMethod(String exMethod) {
		this.exMethod = exMethod;
	}

	public String getExNote() {
		return this.exNote;
	}

	public void setExNote(String exNote) {
		this.exNote = exNote;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

}
