package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * AssocPerf generated by hbm2java
 */
public class AssocPerf implements java.io.Serializable {

	private AssocPerfId id;

	public AssocPerf() {
	}

	public AssocPerf(AssocPerfId id) {
		this.id = id;
	}

	public AssocPerfId getId() {
		return this.id;
	}

	public void setId(AssocPerfId id) {
		this.id = id;
	}

}
