package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * AssocLedgersId generated by hbm2java
 */
public class AssocLedgersId implements java.io.Serializable {

	private int assocId;
	private int ledgerNum;

	public AssocLedgersId() {
	}

	public AssocLedgersId(int assocId, int ledgerNum) {
		this.assocId = assocId;
		this.ledgerNum = ledgerNum;
	}

	public int getAssocId() {
		return this.assocId;
	}

	public void setAssocId(int assocId) {
		this.assocId = assocId;
	}

	public int getLedgerNum() {
		return this.ledgerNum;
	}

	public void setLedgerNum(int ledgerNum) {
		this.ledgerNum = ledgerNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssocLedgersId))
			return false;
		AssocLedgersId castOther = (AssocLedgersId) other;

		return (this.getAssocId() == castOther.getAssocId()) && (this.getLedgerNum() == castOther.getLedgerNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAssocId();
		result = 37 * result + this.getLedgerNum();
		return result;
	}

}
