package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AssocPerfId generated by hbm2java
 */
public class AssocPerfId implements java.io.Serializable {

	private Integer assocId;
	private Date runStart;
	private String assocTitle;
	private Date titleDate;
	private String downIds;
	private Integer numCust;
	private Integer numRes;
	private Integer personScore;
	private Integer teamScore;

	public AssocPerfId() {
	}

	public AssocPerfId(Integer assocId, Date runStart, String assocTitle, Date titleDate, String downIds,
			Integer numCust, Integer numRes, Integer personScore, Integer teamScore) {
		this.assocId = assocId;
		this.runStart = runStart;
		this.assocTitle = assocTitle;
		this.titleDate = titleDate;
		this.downIds = downIds;
		this.numCust = numCust;
		this.numRes = numRes;
		this.personScore = personScore;
		this.teamScore = teamScore;
	}

	public Integer getAssocId() {
		return this.assocId;
	}

	public void setAssocId(Integer assocId) {
		this.assocId = assocId;
	}

	public Date getRunStart() {
		return this.runStart;
	}

	public void setRunStart(Date runStart) {
		this.runStart = runStart;
	}

	public String getAssocTitle() {
		return this.assocTitle;
	}

	public void setAssocTitle(String assocTitle) {
		this.assocTitle = assocTitle;
	}

	public Date getTitleDate() {
		return this.titleDate;
	}

	public void setTitleDate(Date titleDate) {
		this.titleDate = titleDate;
	}

	public String getDownIds() {
		return this.downIds;
	}

	public void setDownIds(String downIds) {
		this.downIds = downIds;
	}

	public Integer getNumCust() {
		return this.numCust;
	}

	public void setNumCust(Integer numCust) {
		this.numCust = numCust;
	}

	public Integer getNumRes() {
		return this.numRes;
	}

	public void setNumRes(Integer numRes) {
		this.numRes = numRes;
	}

	public Integer getPersonScore() {
		return this.personScore;
	}

	public void setPersonScore(Integer personScore) {
		this.personScore = personScore;
	}

	public Integer getTeamScore() {
		return this.teamScore;
	}

	public void setTeamScore(Integer teamScore) {
		this.teamScore = teamScore;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssocPerfId))
			return false;
		AssocPerfId castOther = (AssocPerfId) other;

		return ((this.getAssocId() == castOther.getAssocId()) || (this.getAssocId() != null
				&& castOther.getAssocId() != null && this.getAssocId().equals(castOther.getAssocId())))
				&& ((this.getRunStart() == castOther.getRunStart()) || (this.getRunStart() != null
						&& castOther.getRunStart() != null && this.getRunStart().equals(castOther.getRunStart())))
				&& ((this.getAssocTitle() == castOther.getAssocTitle()) || (this.getAssocTitle() != null
						&& castOther.getAssocTitle() != null && this.getAssocTitle().equals(castOther.getAssocTitle())))
				&& ((this.getTitleDate() == castOther.getTitleDate()) || (this.getTitleDate() != null
						&& castOther.getTitleDate() != null && this.getTitleDate().equals(castOther.getTitleDate())))
				&& ((this.getDownIds() == castOther.getDownIds()) || (this.getDownIds() != null
						&& castOther.getDownIds() != null && this.getDownIds().equals(castOther.getDownIds())))
				&& ((this.getNumCust() == castOther.getNumCust()) || (this.getNumCust() != null
						&& castOther.getNumCust() != null && this.getNumCust().equals(castOther.getNumCust())))
				&& ((this.getNumRes() == castOther.getNumRes()) || (this.getNumRes() != null
						&& castOther.getNumRes() != null && this.getNumRes().equals(castOther.getNumRes())))
				&& ((this.getPersonScore() == castOther.getPersonScore())
						|| (this.getPersonScore() != null && castOther.getPersonScore() != null
								&& this.getPersonScore().equals(castOther.getPersonScore())))
				&& ((this.getTeamScore() == castOther.getTeamScore()) || (this.getTeamScore() != null
						&& castOther.getTeamScore() != null && this.getTeamScore().equals(castOther.getTeamScore())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAssocId() == null ? 0 : this.getAssocId().hashCode());
		result = 37 * result + (getRunStart() == null ? 0 : this.getRunStart().hashCode());
		result = 37 * result + (getAssocTitle() == null ? 0 : this.getAssocTitle().hashCode());
		result = 37 * result + (getTitleDate() == null ? 0 : this.getTitleDate().hashCode());
		result = 37 * result + (getDownIds() == null ? 0 : this.getDownIds().hashCode());
		result = 37 * result + (getNumCust() == null ? 0 : this.getNumCust().hashCode());
		result = 37 * result + (getNumRes() == null ? 0 : this.getNumRes().hashCode());
		result = 37 * result + (getPersonScore() == null ? 0 : this.getPersonScore().hashCode());
		result = 37 * result + (getTeamScore() == null ? 0 : this.getTeamScore().hashCode());
		return result;
	}

}
