package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * ChoicesId generated by hbm2java
 */
public class ChoicesId implements java.io.Serializable {

	private int resId;
	private int itemNum;
	private int chNum;

	public ChoicesId() {
	}

	public ChoicesId(int resId, int itemNum, int chNum) {
		this.resId = resId;
		this.itemNum = itemNum;
		this.chNum = chNum;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(int itemNum) {
		this.itemNum = itemNum;
	}

	public int getChNum() {
		return this.chNum;
	}

	public void setChNum(int chNum) {
		this.chNum = chNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChoicesId))
			return false;
		ChoicesId castOther = (ChoicesId) other;

		return (this.getResId() == castOther.getResId()) && (this.getItemNum() == castOther.getItemNum())
				&& (this.getChNum() == castOther.getChNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getItemNum();
		result = 37 * result + this.getChNum();
		return result;
	}

}
