package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * ChValuesId generated by hbm2java
 */
public class ChValuesId implements java.io.Serializable {

	private int resId;
	private int chNum;
	private String valueName;

	public ChValuesId() {
	}

	public ChValuesId(int resId, int chNum, String valueName) {
		this.resId = resId;
		this.chNum = chNum;
		this.valueName = valueName;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getChNum() {
		return this.chNum;
	}

	public void setChNum(int chNum) {
		this.chNum = chNum;
	}

	public String getValueName() {
		return this.valueName;
	}

	public void setValueName(String valueName) {
		this.valueName = valueName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChValuesId))
			return false;
		ChValuesId castOther = (ChValuesId) other;

		return (this.getResId() == castOther.getResId()) && (this.getChNum() == castOther.getChNum())
				&& ((this.getValueName() == castOther.getValueName()) || (this.getValueName() != null
						&& castOther.getValueName() != null && this.getValueName().equals(castOther.getValueName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getChNum();
		result = 37 * result + (getValueName() == null ? 0 : this.getValueName().hashCode());
		return result;
	}

}
