package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * CustLedgers generated by hbm2java
 */
public class CustLedgers implements java.io.Serializable {

	private CustLedgersId id;
	private String custName;
	private Date ledgerDate;
	private Integer resId;
	private Integer orderNum;
	private String resName;
	private Float chargeAmt;
	private Float payAmt;
	private String payMethod;
	private String note;
	private Float balance;

	public CustLedgers() {
	}

	public CustLedgers(CustLedgersId id) {
		this.id = id;
	}

	public CustLedgers(CustLedgersId id, String custName, Date ledgerDate, Integer resId, Integer orderNum,
			String resName, Float chargeAmt, Float payAmt, String payMethod, String note, Float balance) {
		this.id = id;
		this.custName = custName;
		this.ledgerDate = ledgerDate;
		this.resId = resId;
		this.orderNum = orderNum;
		this.resName = resName;
		this.chargeAmt = chargeAmt;
		this.payAmt = payAmt;
		this.payMethod = payMethod;
		this.note = note;
		this.balance = balance;
	}

	public CustLedgersId getId() {
		return this.id;
	}

	public void setId(CustLedgersId id) {
		this.id = id;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public Date getLedgerDate() {
		return this.ledgerDate;
	}

	public void setLedgerDate(Date ledgerDate) {
		this.ledgerDate = ledgerDate;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public Float getChargeAmt() {
		return this.chargeAmt;
	}

	public void setChargeAmt(Float chargeAmt) {
		this.chargeAmt = chargeAmt;
	}

	public Float getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(Float payAmt) {
		this.payAmt = payAmt;
	}

	public String getPayMethod() {
		return this.payMethod;
	}

	public void setPayMethod(String payMethod) {
		this.payMethod = payMethod;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

}
