package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private Integer custId;
	private Date insertDate;
	private Date cancelDate;
	private String firstName;
	private String middleName;
	private String lastName;
	private String nickName;
	private String telephoneNumber;
	private String otherPhone;
	private String addrStNum;
	private String city;
	private String state;
	private String zip;
	private Float latitude;
	private Float longitude;
	private String emailAddress;
	private String password;
	private String cardNumber;
	private String cardType;
	private String cardName;
	private Date cardExp;
	private String cardCode;
	private String billZip;
	private String billAddr;
	private String cardNumber1;
	private String cardType1;
	private String cardName1;
	private Date cardExp1;
	private String cardCode1;
	private String billZip1;
	private String billAddr1;
	private String paypalNum;
	private Integer recomenderId;
	private String recomType;
	private String promoCode;
	private String adChannel;

	public Customers() {
	}

	public Customers(Date insertDate, String firstName, String lastName, String telephoneNumber, String addrStNum,
			String city, String state, String zip, String emailAddress, String password) {
		this.insertDate = insertDate;
		this.firstName = firstName;
		this.lastName = lastName;
		this.telephoneNumber = telephoneNumber;
		this.addrStNum = addrStNum;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.emailAddress = emailAddress;
		this.password = password;
	}

	public Customers(Date insertDate, Date cancelDate, String firstName, String middleName, String lastName,
			String nickName, String telephoneNumber, String otherPhone, String addrStNum, String city, String state,
			String zip, Float latitude, Float longitude, String emailAddress, String password, String cardNumber,
			String cardType, String cardName, Date cardExp, String cardCode, String billZip, String billAddr,
			String cardNumber1, String cardType1, String cardName1, Date cardExp1, String cardCode1, String billZip1,
			String billAddr1, String paypalNum, Integer recomenderId, String recomType, String promoCode,
			String adChannel) {
		this.insertDate = insertDate;
		this.cancelDate = cancelDate;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.nickName = nickName;
		this.telephoneNumber = telephoneNumber;
		this.otherPhone = otherPhone;
		this.addrStNum = addrStNum;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.latitude = latitude;
		this.longitude = longitude;
		this.emailAddress = emailAddress;
		this.password = password;
		this.cardNumber = cardNumber;
		this.cardType = cardType;
		this.cardName = cardName;
		this.cardExp = cardExp;
		this.cardCode = cardCode;
		this.billZip = billZip;
		this.billAddr = billAddr;
		this.cardNumber1 = cardNumber1;
		this.cardType1 = cardType1;
		this.cardName1 = cardName1;
		this.cardExp1 = cardExp1;
		this.cardCode1 = cardCode1;
		this.billZip1 = billZip1;
		this.billAddr1 = billAddr1;
		this.paypalNum = paypalNum;
		this.recomenderId = recomenderId;
		this.recomType = recomType;
		this.promoCode = promoCode;
		this.adChannel = adChannel;
	}

	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

	public String getOtherPhone() {
		return this.otherPhone;
	}

	public void setOtherPhone(String otherPhone) {
		this.otherPhone = otherPhone;
	}

	public String getAddrStNum() {
		return this.addrStNum;
	}

	public void setAddrStNum(String addrStNum) {
		this.addrStNum = addrStNum;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	public Date getCardExp() {
		return this.cardExp;
	}

	public void setCardExp(Date cardExp) {
		this.cardExp = cardExp;
	}

	public String getCardCode() {
		return this.cardCode;
	}

	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}

	public String getBillZip() {
		return this.billZip;
	}

	public void setBillZip(String billZip) {
		this.billZip = billZip;
	}

	public String getBillAddr() {
		return this.billAddr;
	}

	public void setBillAddr(String billAddr) {
		this.billAddr = billAddr;
	}

	public String getCardNumber1() {
		return this.cardNumber1;
	}

	public void setCardNumber1(String cardNumber1) {
		this.cardNumber1 = cardNumber1;
	}

	public String getCardType1() {
		return this.cardType1;
	}

	public void setCardType1(String cardType1) {
		this.cardType1 = cardType1;
	}

	public String getCardName1() {
		return this.cardName1;
	}

	public void setCardName1(String cardName1) {
		this.cardName1 = cardName1;
	}

	public Date getCardExp1() {
		return this.cardExp1;
	}

	public void setCardExp1(Date cardExp1) {
		this.cardExp1 = cardExp1;
	}

	public String getCardCode1() {
		return this.cardCode1;
	}

	public void setCardCode1(String cardCode1) {
		this.cardCode1 = cardCode1;
	}

	public String getBillZip1() {
		return this.billZip1;
	}

	public void setBillZip1(String billZip1) {
		this.billZip1 = billZip1;
	}

	public String getBillAddr1() {
		return this.billAddr1;
	}

	public void setBillAddr1(String billAddr1) {
		this.billAddr1 = billAddr1;
	}

	public String getPaypalNum() {
		return this.paypalNum;
	}

	public void setPaypalNum(String paypalNum) {
		this.paypalNum = paypalNum;
	}

	public Integer getRecomenderId() {
		return this.recomenderId;
	}

	public void setRecomenderId(Integer recomenderId) {
		this.recomenderId = recomenderId;
	}

	public String getRecomType() {
		return this.recomType;
	}

	public void setRecomType(String recomType) {
		this.recomType = recomType;
	}

	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

	public String getAdChannel() {
		return this.adChannel;
	}

	public void setAdChannel(String adChannel) {
		this.adChannel = adChannel;
	}

}
