package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * FavoritesId generated by hbm2java
 */
public class FavoritesId implements java.io.Serializable {

	private int custId;
	private int favId;

	public FavoritesId() {
	}

	public FavoritesId(int custId, int favId) {
		this.custId = custId;
		this.favId = favId;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public int getFavId() {
		return this.favId;
	}

	public void setFavId(int favId) {
		this.favId = favId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesId))
			return false;
		FavoritesId castOther = (FavoritesId) other;

		return (this.getCustId() == castOther.getCustId()) && (this.getFavId() == castOther.getFavId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustId();
		result = 37 * result + this.getFavId();
		return result;
	}

}
