package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * Favorites generated by hbm2java
 */
public class Favorites implements java.io.Serializable {

	private FavoritesId id;
	private String favName;

	public Favorites() {
	}

	public Favorites(FavoritesId id) {
		this.id = id;
	}

	public Favorites(FavoritesId id, String favName) {
		this.id = id;
		this.favName = favName;
	}

	public FavoritesId getId() {
		return this.id;
	}

	public void setId(FavoritesId id) {
		this.id = id;
	}

	public String getFavName() {
		return this.favName;
	}

	public void setFavName(String favName) {
		this.favName = favName;
	}

}
