package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ForSales generated by hbm2java
 */
public class ForSales implements java.io.Serializable {

	private Integer saleId;
	private Integer resId;
	private String resName;
	private String title;
	private Date availDate;
	private String type;
	private Date insertDate;
	private String saleDesc;
	private Float salePrice;

	public ForSales() {
	}

	public ForSales(Integer resId, String resName, String title, Date availDate, String type, Date insertDate,
			String saleDesc, Float salePrice) {
		this.resId = resId;
		this.resName = resName;
		this.title = title;
		this.availDate = availDate;
		this.type = type;
		this.insertDate = insertDate;
		this.saleDesc = saleDesc;
		this.salePrice = salePrice;
	}

	public Integer getSaleId() {
		return this.saleId;
	}

	public void setSaleId(Integer saleId) {
		this.saleId = saleId;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getAvailDate() {
		return this.availDate;
	}

	public void setAvailDate(Date availDate) {
		this.availDate = availDate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getSaleDesc() {
		return this.saleDesc;
	}

	public void setSaleDesc(String saleDesc) {
		this.saleDesc = saleDesc;
	}

	public Float getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Float salePrice) {
		this.salePrice = salePrice;
	}

}
