package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Hirings generated by hbm2java
 */
public class Hirings implements java.io.Serializable {

	private Integer hireId;
	private Integer resId;
	private String resName;
	private String title;
	private String hireType;
	private Date insertDate;
	private String jobDesc;
	private Float payRate;
	private String payPer;
	private String workTimes;

	public Hirings() {
	}

	public Hirings(Integer resId, String resName, String title, String hireType, Date insertDate, String jobDesc,
			Float payRate, String payPer, String workTimes) {
		this.resId = resId;
		this.resName = resName;
		this.title = title;
		this.hireType = hireType;
		this.insertDate = insertDate;
		this.jobDesc = jobDesc;
		this.payRate = payRate;
		this.payPer = payPer;
		this.workTimes = workTimes;
	}

	public Integer getHireId() {
		return this.hireId;
	}

	public void setHireId(Integer hireId) {
		this.hireId = hireId;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getHireType() {
		return this.hireType;
	}

	public void setHireType(String hireType) {
		this.hireType = hireType;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	public Float getPayRate() {
		return this.payRate;
	}

	public void setPayRate(Float payRate) {
		this.payRate = payRate;
	}

	public String getPayPer() {
		return this.payPer;
	}

	public void setPayPer(String payPer) {
		this.payPer = payPer;
	}

	public String getWorkTimes() {
		return this.workTimes;
	}

	public void setWorkTimes(String workTimes) {
		this.workTimes = workTimes;
	}

}
