package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * Inpln generated by hbm2java
 */
public class Inpln implements java.io.Serializable {

	private int lnnbr;
	private String lnnam;

	public Inpln() {
	}

	public Inpln(int lnnbr) {
		this.lnnbr = lnnbr;
	}

	public Inpln(int lnnbr, String lnnam) {
		this.lnnbr = lnnbr;
		this.lnnam = lnnam;
	}

	public int getLnnbr() {
		return this.lnnbr;
	}

	public void setLnnbr(int lnnbr) {
		this.lnnbr = lnnbr;
	}

	public String getLnnam() {
		return this.lnnam;
	}

	public void setLnnam(String lnnam) {
		this.lnnam = lnnam;
	}

}
