package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * ItemsId generated by hbm2java
 */
public class ItemsId implements java.io.Serializable {

	private int resId;
	private int itemNum;

	public ItemsId() {
	}

	public ItemsId(int resId, int itemNum) {
		this.resId = resId;
		this.itemNum = itemNum;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(int itemNum) {
		this.itemNum = itemNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemsId))
			return false;
		ItemsId castOther = (ItemsId) other;

		return (this.getResId() == castOther.getResId()) && (this.getItemNum() == castOther.getItemNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getItemNum();
		return result;
	}

}
