package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable {

	private ItemsId id;
	private String secName;
	private String itemName;
	private String description;
	private Float basePrice;
	private Byte numChoice;

	public Items() {
	}

	public Items(ItemsId id, String itemName) {
		this.id = id;
		this.itemName = itemName;
	}

	public Items(ItemsId id, String secName, String itemName, String description, Float basePrice, Byte numChoice) {
		this.id = id;
		this.secName = secName;
		this.itemName = itemName;
		this.description = description;
		this.basePrice = basePrice;
		this.numChoice = numChoice;
	}

	public ItemsId getId() {
		return this.id;
	}

	public void setId(ItemsId id) {
		this.id = id;
	}

	public String getSecName() {
		return this.secName;
	}

	public void setSecName(String secName) {
		this.secName = secName;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(Float basePrice) {
		this.basePrice = basePrice;
	}

	public Byte getNumChoice() {
		return this.numChoice;
	}

	public void setNumChoice(Byte numChoice) {
		this.numChoice = numChoice;
	}

}
