package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * LineItemsId generated by hbm2java
 */
public class LineItemsId implements java.io.Serializable {

	private int resId;
	private int orderNum;
	private int lineNum;

	public LineItemsId() {
	}

	public LineItemsId(int resId, int orderNum, int lineNum) {
		this.resId = resId;
		this.orderNum = orderNum;
		this.lineNum = lineNum;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

	public int getLineNum() {
		return this.lineNum;
	}

	public void setLineNum(int lineNum) {
		this.lineNum = lineNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineItemsId))
			return false;
		LineItemsId castOther = (LineItemsId) other;

		return (this.getResId() == castOther.getResId()) && (this.getOrderNum() == castOther.getOrderNum())
				&& (this.getLineNum() == castOther.getLineNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getOrderNum();
		result = 37 * result + this.getLineNum();
		return result;
	}

}
