package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

	private MessagesId id;
	private String email;
	private String phone;
	private String subject;
	private String msgText;
	private String replyText;
	private Boolean replied;
	private Date replyTime;
	private String status;

	public Messages() {
	}

	public Messages(MessagesId id, String email) {
		this.id = id;
		this.email = email;
	}

	public Messages(MessagesId id, String email, String phone, String subject, String msgText, String replyText,
			Boolean replied, Date replyTime, String status) {
		this.id = id;
		this.email = email;
		this.phone = phone;
		this.subject = subject;
		this.msgText = msgText;
		this.replyText = replyText;
		this.replied = replied;
		this.replyTime = replyTime;
		this.status = status;
	}

	public MessagesId getId() {
		return this.id;
	}

	public void setId(MessagesId id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMsgText() {
		return this.msgText;
	}

	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}

	public String getReplyText() {
		return this.replyText;
	}

	public void setReplyText(String replyText) {
		this.replyText = replyText;
	}

	public Boolean getReplied() {
		return this.replied;
	}

	public void setReplied(Boolean replied) {
		this.replied = replied;
	}

	public Date getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
