package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * MessagesId generated by hbm2java
 */
public class MessagesId implements java.io.Serializable {

	private String name;
	private Date msgTime;

	public MessagesId() {
	}

	public MessagesId(String name, Date msgTime) {
		this.name = name;
		this.msgTime = msgTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getMsgTime() {
		return this.msgTime;
	}

	public void setMsgTime(Date msgTime) {
		this.msgTime = msgTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessagesId))
			return false;
		MessagesId castOther = (MessagesId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getMsgTime() == castOther.getMsgTime()) || (this.getMsgTime() != null
						&& castOther.getMsgTime() != null && this.getMsgTime().equals(castOther.getMsgTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getMsgTime() == null ? 0 : this.getMsgTime().hashCode());
		return result;
	}

}
