package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * ResLedgersId generated by hbm2java
 */
public class ResLedgersId implements java.io.Serializable {

	private int resId;
	private int ledgerNum;

	public ResLedgersId() {
	}

	public ResLedgersId(int resId, int ledgerNum) {
		this.resId = resId;
		this.ledgerNum = ledgerNum;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getLedgerNum() {
		return this.ledgerNum;
	}

	public void setLedgerNum(int ledgerNum) {
		this.ledgerNum = ledgerNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResLedgersId))
			return false;
		ResLedgersId castOther = (ResLedgersId) other;

		return (this.getResId() == castOther.getResId()) && (this.getLedgerNum() == castOther.getLedgerNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getLedgerNum();
		return result;
	}

}
