package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * ResReviews generated by hbm2java
 */
public class ResReviews implements java.io.Serializable {

	private ResReviewsId id;
	private String custName;
	private String resName;
	private Float foodQuality;
	private Float price;
	private Float prompt;
	private Float overall;
	private String revTitle;
	private String comment;
	private String resReply;
	private Integer helpful;
	private Integer noHelp;
	private Integer numFbk;
	private String feedback;

	public ResReviews() {
	}

	public ResReviews(ResReviewsId id) {
		this.id = id;
	}

	public ResReviews(ResReviewsId id, String custName, String resName, Float foodQuality, Float price, Float prompt,
			Float overall, String revTitle, String comment, String resReply, Integer helpful, Integer noHelp,
			Integer numFbk, String feedback) {
		this.id = id;
		this.custName = custName;
		this.resName = resName;
		this.foodQuality = foodQuality;
		this.price = price;
		this.prompt = prompt;
		this.overall = overall;
		this.revTitle = revTitle;
		this.comment = comment;
		this.resReply = resReply;
		this.helpful = helpful;
		this.noHelp = noHelp;
		this.numFbk = numFbk;
		this.feedback = feedback;
	}

	public ResReviewsId getId() {
		return this.id;
	}

	public void setId(ResReviewsId id) {
		this.id = id;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public Float getFoodQuality() {
		return this.foodQuality;
	}

	public void setFoodQuality(Float foodQuality) {
		this.foodQuality = foodQuality;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Float getPrompt() {
		return this.prompt;
	}

	public void setPrompt(Float prompt) {
		this.prompt = prompt;
	}

	public Float getOverall() {
		return this.overall;
	}

	public void setOverall(Float overall) {
		this.overall = overall;
	}

	public String getRevTitle() {
		return this.revTitle;
	}

	public void setRevTitle(String revTitle) {
		this.revTitle = revTitle;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getResReply() {
		return this.resReply;
	}

	public void setResReply(String resReply) {
		this.resReply = resReply;
	}

	public Integer getHelpful() {
		return this.helpful;
	}

	public void setHelpful(Integer helpful) {
		this.helpful = helpful;
	}

	public Integer getNoHelp() {
		return this.noHelp;
	}

	public void setNoHelp(Integer noHelp) {
		this.noHelp = noHelp;
	}

	public Integer getNumFbk() {
		return this.numFbk;
	}

	public void setNumFbk(Integer numFbk) {
		this.numFbk = numFbk;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

}
