package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ResReviewsId generated by hbm2java
 */
public class ResReviewsId implements java.io.Serializable {

	private int resId;
	private int custId;
	private Date revDate;

	public ResReviewsId() {
	}

	public ResReviewsId(int resId, int custId, Date revDate) {
		this.resId = resId;
		this.custId = custId;
		this.revDate = revDate;
	}

	public int getResId() {
		return this.resId;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public Date getRevDate() {
		return this.revDate;
	}

	public void setRevDate(Date revDate) {
		this.revDate = revDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResReviewsId))
			return false;
		ResReviewsId castOther = (ResReviewsId) other;

		return (this.getResId() == castOther.getResId()) && (this.getCustId() == castOther.getCustId())
				&& ((this.getRevDate() == castOther.getRevDate()) || (this.getRevDate() != null
						&& castOther.getRevDate() != null && this.getRevDate().equals(castOther.getRevDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResId();
		result = 37 * result + this.getCustId();
		result = 37 * result + (getRevDate() == null ? 0 : this.getRevDate().hashCode());
		return result;
	}

}
