package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Restaurants generated by hbm2java
 */
public class Restaurants implements java.io.Serializable {

	private Integer resId;
	private String resName;
	private String altName;
	private Date foundYear;
	private String categories;
	private Date insertDate;
	private Date cancelDate;
	private String hasMenu;
	private String inputBy;
	private String note;
	private String telephoneNumber;
	private String otherPhone;
	private String addrStNum;
	private String city;
	private String state;
	private String zip;
	private Float latitude;
	private Float longitude;
	private String emailAddress;
	private String passwd;
	private byte question;
	private String answer;
	private String website;
	private Date monFrom;
	private Date monTo;
	private Date tueFrom;
	private Date tueTo;
	private Date wedFrom;
	private Date wedTo;
	private Date thuFrom;
	private Date thuTo;
	private Date friFrom;
	private Date friTo;
	private Date satFrom;
	private Date satTo;
	private Date sunFrom;
	private Date sunTo;
	private String closedDays;
	private String delivery;
	private String deliBy;
	private BigDecimal deliMin;
	private BigDecimal deliFee;
	private String deliPolicy;
	private Float deliRadius;
	private String deliZips;
	private String deliStreets;
	private String pickup;
	private String dineIn;
	private String reserve;
	private String forKids;
	private String forGroup;
	private String parking;
	private String wifi;
	private String breakfast;
	private String lunch;
	private String dinner;
	private String lateNight;
	private String coupon;
	private String bankName;
	private String bankPhone;
	private String bankAddr;
	private String bankRouteNum;
	private String bankAccNum;
	private String mgrName;
	private String mgrPhone;
	private String mgrEmail;
	private String mgrPasswd;

	public Restaurants() {
	}

	public Restaurants(String resName, String categories, Date insertDate, String telephoneNumber, String addrStNum,
			String city, String state, String zip, String emailAddress, String passwd, byte question) {
		this.resName = resName;
		this.categories = categories;
		this.insertDate = insertDate;
		this.telephoneNumber = telephoneNumber;
		this.addrStNum = addrStNum;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.emailAddress = emailAddress;
		this.passwd = passwd;
		this.question = question;
	}

	public Restaurants(String resName, String altName, Date foundYear, String categories, Date insertDate,
			Date cancelDate, String hasMenu, String inputBy, String note, String telephoneNumber, String otherPhone,
			String addrStNum, String city, String state, String zip, Float latitude, Float longitude,
			String emailAddress, String passwd, byte question, String answer, String website, Date monFrom, Date monTo,
			Date tueFrom, Date tueTo, Date wedFrom, Date wedTo, Date thuFrom, Date thuTo, Date friFrom, Date friTo,
			Date satFrom, Date satTo, Date sunFrom, Date sunTo, String closedDays, String delivery, String deliBy,
			BigDecimal deliMin, BigDecimal deliFee, String deliPolicy, Float deliRadius, String deliZips,
			String deliStreets, String pickup, String dineIn, String reserve, String forKids, String forGroup,
			String parking, String wifi, String breakfast, String lunch, String dinner, String lateNight, String coupon,
			String bankName, String bankPhone, String bankAddr, String bankRouteNum, String bankAccNum, String mgrName,
			String mgrPhone, String mgrEmail, String mgrPasswd) {
		this.resName = resName;
		this.altName = altName;
		this.foundYear = foundYear;
		this.categories = categories;
		this.insertDate = insertDate;
		this.cancelDate = cancelDate;
		this.hasMenu = hasMenu;
		this.inputBy = inputBy;
		this.note = note;
		this.telephoneNumber = telephoneNumber;
		this.otherPhone = otherPhone;
		this.addrStNum = addrStNum;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.latitude = latitude;
		this.longitude = longitude;
		this.emailAddress = emailAddress;
		this.passwd = passwd;
		this.question = question;
		this.answer = answer;
		this.website = website;
		this.monFrom = monFrom;
		this.monTo = monTo;
		this.tueFrom = tueFrom;
		this.tueTo = tueTo;
		this.wedFrom = wedFrom;
		this.wedTo = wedTo;
		this.thuFrom = thuFrom;
		this.thuTo = thuTo;
		this.friFrom = friFrom;
		this.friTo = friTo;
		this.satFrom = satFrom;
		this.satTo = satTo;
		this.sunFrom = sunFrom;
		this.sunTo = sunTo;
		this.closedDays = closedDays;
		this.delivery = delivery;
		this.deliBy = deliBy;
		this.deliMin = deliMin;
		this.deliFee = deliFee;
		this.deliPolicy = deliPolicy;
		this.deliRadius = deliRadius;
		this.deliZips = deliZips;
		this.deliStreets = deliStreets;
		this.pickup = pickup;
		this.dineIn = dineIn;
		this.reserve = reserve;
		this.forKids = forKids;
		this.forGroup = forGroup;
		this.parking = parking;
		this.wifi = wifi;
		this.breakfast = breakfast;
		this.lunch = lunch;
		this.dinner = dinner;
		this.lateNight = lateNight;
		this.coupon = coupon;
		this.bankName = bankName;
		this.bankPhone = bankPhone;
		this.bankAddr = bankAddr;
		this.bankRouteNum = bankRouteNum;
		this.bankAccNum = bankAccNum;
		this.mgrName = mgrName;
		this.mgrPhone = mgrPhone;
		this.mgrEmail = mgrEmail;
		this.mgrPasswd = mgrPasswd;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	public String getAltName() {
		return this.altName;
	}

	public void setAltName(String altName) {
		this.altName = altName;
	}

	public Date getFoundYear() {
		return this.foundYear;
	}

	public void setFoundYear(Date foundYear) {
		this.foundYear = foundYear;
	}

	public String getCategories() {
		return this.categories;
	}

	public void setCategories(String categories) {
		this.categories = categories;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	public String getHasMenu() {
		return this.hasMenu;
	}

	public void setHasMenu(String hasMenu) {
		this.hasMenu = hasMenu;
	}

	public String getInputBy() {
		return this.inputBy;
	}

	public void setInputBy(String inputBy) {
		this.inputBy = inputBy;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getTelephoneNumber() {
		return this.telephoneNumber;
	}

	public void setTelephoneNumber(String telephoneNumber) {
		this.telephoneNumber = telephoneNumber;
	}

	public String getOtherPhone() {
		return this.otherPhone;
	}

	public void setOtherPhone(String otherPhone) {
		this.otherPhone = otherPhone;
	}

	public String getAddrStNum() {
		return this.addrStNum;
	}

	public void setAddrStNum(String addrStNum) {
		this.addrStNum = addrStNum;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public byte getQuestion() {
		return this.question;
	}

	public void setQuestion(byte question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getMonFrom() {
		return this.monFrom;
	}

	public void setMonFrom(Date monFrom) {
		this.monFrom = monFrom;
	}

	public Date getMonTo() {
		return this.monTo;
	}

	public void setMonTo(Date monTo) {
		this.monTo = monTo;
	}

	public Date getTueFrom() {
		return this.tueFrom;
	}

	public void setTueFrom(Date tueFrom) {
		this.tueFrom = tueFrom;
	}

	public Date getTueTo() {
		return this.tueTo;
	}

	public void setTueTo(Date tueTo) {
		this.tueTo = tueTo;
	}

	public Date getWedFrom() {
		return this.wedFrom;
	}

	public void setWedFrom(Date wedFrom) {
		this.wedFrom = wedFrom;
	}

	public Date getWedTo() {
		return this.wedTo;
	}

	public void setWedTo(Date wedTo) {
		this.wedTo = wedTo;
	}

	public Date getThuFrom() {
		return this.thuFrom;
	}

	public void setThuFrom(Date thuFrom) {
		this.thuFrom = thuFrom;
	}

	public Date getThuTo() {
		return this.thuTo;
	}

	public void setThuTo(Date thuTo) {
		this.thuTo = thuTo;
	}

	public Date getFriFrom() {
		return this.friFrom;
	}

	public void setFriFrom(Date friFrom) {
		this.friFrom = friFrom;
	}

	public Date getFriTo() {
		return this.friTo;
	}

	public void setFriTo(Date friTo) {
		this.friTo = friTo;
	}

	public Date getSatFrom() {
		return this.satFrom;
	}

	public void setSatFrom(Date satFrom) {
		this.satFrom = satFrom;
	}

	public Date getSatTo() {
		return this.satTo;
	}

	public void setSatTo(Date satTo) {
		this.satTo = satTo;
	}

	public Date getSunFrom() {
		return this.sunFrom;
	}

	public void setSunFrom(Date sunFrom) {
		this.sunFrom = sunFrom;
	}

	public Date getSunTo() {
		return this.sunTo;
	}

	public void setSunTo(Date sunTo) {
		this.sunTo = sunTo;
	}

	public String getClosedDays() {
		return this.closedDays;
	}

	public void setClosedDays(String closedDays) {
		this.closedDays = closedDays;
	}

	public String getDelivery() {
		return this.delivery;
	}

	public void setDelivery(String delivery) {
		this.delivery = delivery;
	}

	public String getDeliBy() {
		return this.deliBy;
	}

	public void setDeliBy(String deliBy) {
		this.deliBy = deliBy;
	}

	public BigDecimal getDeliMin() {
		return this.deliMin;
	}

	public void setDeliMin(BigDecimal deliMin) {
		this.deliMin = deliMin;
	}

	public BigDecimal getDeliFee() {
		return this.deliFee;
	}

	public void setDeliFee(BigDecimal deliFee) {
		this.deliFee = deliFee;
	}

	public String getDeliPolicy() {
		return this.deliPolicy;
	}

	public void setDeliPolicy(String deliPolicy) {
		this.deliPolicy = deliPolicy;
	}

	public Float getDeliRadius() {
		return this.deliRadius;
	}

	public void setDeliRadius(Float deliRadius) {
		this.deliRadius = deliRadius;
	}

	public String getDeliZips() {
		return this.deliZips;
	}

	public void setDeliZips(String deliZips) {
		this.deliZips = deliZips;
	}

	public String getDeliStreets() {
		return this.deliStreets;
	}

	public void setDeliStreets(String deliStreets) {
		this.deliStreets = deliStreets;
	}

	public String getPickup() {
		return this.pickup;
	}

	public void setPickup(String pickup) {
		this.pickup = pickup;
	}

	public String getDineIn() {
		return this.dineIn;
	}

	public void setDineIn(String dineIn) {
		this.dineIn = dineIn;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getForKids() {
		return this.forKids;
	}

	public void setForKids(String forKids) {
		this.forKids = forKids;
	}

	public String getForGroup() {
		return this.forGroup;
	}

	public void setForGroup(String forGroup) {
		this.forGroup = forGroup;
	}

	public String getParking() {
		return this.parking;
	}

	public void setParking(String parking) {
		this.parking = parking;
	}

	public String getWifi() {
		return this.wifi;
	}

	public void setWifi(String wifi) {
		this.wifi = wifi;
	}

	public String getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(String breakfast) {
		this.breakfast = breakfast;
	}

	public String getLunch() {
		return this.lunch;
	}

	public void setLunch(String lunch) {
		this.lunch = lunch;
	}

	public String getDinner() {
		return this.dinner;
	}

	public void setDinner(String dinner) {
		this.dinner = dinner;
	}

	public String getLateNight() {
		return this.lateNight;
	}

	public void setLateNight(String lateNight) {
		this.lateNight = lateNight;
	}

	public String getCoupon() {
		return this.coupon;
	}

	public void setCoupon(String coupon) {
		this.coupon = coupon;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankPhone() {
		return this.bankPhone;
	}

	public void setBankPhone(String bankPhone) {
		this.bankPhone = bankPhone;
	}

	public String getBankAddr() {
		return this.bankAddr;
	}

	public void setBankAddr(String bankAddr) {
		this.bankAddr = bankAddr;
	}

	public String getBankRouteNum() {
		return this.bankRouteNum;
	}

	public void setBankRouteNum(String bankRouteNum) {
		this.bankRouteNum = bankRouteNum;
	}

	public String getBankAccNum() {
		return this.bankAccNum;
	}

	public void setBankAccNum(String bankAccNum) {
		this.bankAccNum = bankAccNum;
	}

	public String getMgrName() {
		return this.mgrName;
	}

	public void setMgrName(String mgrName) {
		this.mgrName = mgrName;
	}

	public String getMgrPhone() {
		return this.mgrPhone;
	}

	public void setMgrPhone(String mgrPhone) {
		this.mgrPhone = mgrPhone;
	}

	public String getMgrEmail() {
		return this.mgrEmail;
	}

	public void setMgrEmail(String mgrEmail) {
		this.mgrEmail = mgrEmail;
	}

	public String getMgrPasswd() {
		return this.mgrPasswd;
	}

	public void setMgrPasswd(String mgrPasswd) {
		this.mgrPasswd = mgrPasswd;
	}

}
