package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * Sections generated by hbm2java
 */
public class Sections implements java.io.Serializable {

	private SectionsId id;
	private Byte numItem;

	public Sections() {
	}

	public Sections(SectionsId id) {
		this.id = id;
	}

	public Sections(SectionsId id, Byte numItem) {
		this.id = id;
		this.numItem = numItem;
	}

	public SectionsId getId() {
		return this.id;
	}

	public void setId(SectionsId id) {
		this.id = id;
	}

	public Byte getNumItem() {
		return this.numItem;
	}

	public void setNumItem(Byte numItem) {
		this.numItem = numItem;
	}

}
