package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

/**
 * SiteReviews generated by hbm2java
 */
public class SiteReviews implements java.io.Serializable {

	private SiteReviewsId id;
	private Integer likes;
	private Integer dislikes;
	private float siteStars;
	private float phoneStars;
	private String revTitle;
	private String comment;
	private String ourReply;
	private Integer helpful;
	private Integer noHelp;
	private Integer numFbk;
	private String feedback;

	public SiteReviews() {
	}

	public SiteReviews(SiteReviewsId id, float siteStars, float phoneStars) {
		this.id = id;
		this.siteStars = siteStars;
		this.phoneStars = phoneStars;
	}

	public SiteReviews(SiteReviewsId id, Integer likes, Integer dislikes, float siteStars, float phoneStars,
			String revTitle, String comment, String ourReply, Integer helpful, Integer noHelp, Integer numFbk,
			String feedback) {
		this.id = id;
		this.likes = likes;
		this.dislikes = dislikes;
		this.siteStars = siteStars;
		this.phoneStars = phoneStars;
		this.revTitle = revTitle;
		this.comment = comment;
		this.ourReply = ourReply;
		this.helpful = helpful;
		this.noHelp = noHelp;
		this.numFbk = numFbk;
		this.feedback = feedback;
	}

	public SiteReviewsId getId() {
		return this.id;
	}

	public void setId(SiteReviewsId id) {
		this.id = id;
	}

	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	public Integer getDislikes() {
		return this.dislikes;
	}

	public void setDislikes(Integer dislikes) {
		this.dislikes = dislikes;
	}

	public float getSiteStars() {
		return this.siteStars;
	}

	public void setSiteStars(float siteStars) {
		this.siteStars = siteStars;
	}

	public float getPhoneStars() {
		return this.phoneStars;
	}

	public void setPhoneStars(float phoneStars) {
		this.phoneStars = phoneStars;
	}

	public String getRevTitle() {
		return this.revTitle;
	}

	public void setRevTitle(String revTitle) {
		this.revTitle = revTitle;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getOurReply() {
		return this.ourReply;
	}

	public void setOurReply(String ourReply) {
		this.ourReply = ourReply;
	}

	public Integer getHelpful() {
		return this.helpful;
	}

	public void setHelpful(Integer helpful) {
		this.helpful = helpful;
	}

	public Integer getNoHelp() {
		return this.noHelp;
	}

	public void setNoHelp(Integer noHelp) {
		this.noHelp = noHelp;
	}

	public Integer getNumFbk() {
		return this.numFbk;
	}

	public void setNumFbk(Integer numFbk) {
		this.numFbk = numFbk;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

}
