package com.reverseengineering.model;
// Generated Mar 16, 2016 6:54:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SiteReviewsId generated by hbm2java
 */
public class SiteReviewsId implements java.io.Serializable {

	private String revName;
	private Date revTime;

	public SiteReviewsId() {
	}

	public SiteReviewsId(String revName, Date revTime) {
		this.revName = revName;
		this.revTime = revTime;
	}

	public String getRevName() {
		return this.revName;
	}

	public void setRevName(String revName) {
		this.revName = revName;
	}

	public Date getRevTime() {
		return this.revTime;
	}

	public void setRevTime(Date revTime) {
		this.revTime = revTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SiteReviewsId))
			return false;
		SiteReviewsId castOther = (SiteReviewsId) other;

		return ((this.getRevName() == castOther.getRevName()) || (this.getRevName() != null
				&& castOther.getRevName() != null && this.getRevName().equals(castOther.getRevName())))
				&& ((this.getRevTime() == castOther.getRevTime()) || (this.getRevTime() != null
						&& castOther.getRevTime() != null && this.getRevTime().equals(castOther.getRevTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRevName() == null ? 0 : this.getRevName().hashCode());
		result = 37 * result + (getRevTime() == null ? 0 : this.getRevTime().hashCode());
		return result;
	}

}
